import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
// Panel lateral que muestra detalles de un nodo seleccionado (módulo, carpeta o integración)
export const ModulePanel = ({ node, onClose }) => {
    if (!node)
        return null;
    const isModule = node.type === 'module';
    const isFolder = node.type === 'folder';
    const isIntegration = node.type === 'database' || node.type === 'external_api';
    return (_jsxs("aside", { className: `module-panel ${node ? 'module-panel--open' : ''}`, role: "complementary", "aria-label": "Detalles del nodo", children: [_jsxs("div", { className: "module-panel__header", children: [_jsx("h2", { className: "module-panel__title", children: node.name }), _jsx("button", { className: "module-panel__close", onClick: onClose, "aria-label": "Cerrar panel", title: "Cerrar", children: "\u2715" })] }), _jsxs("div", { className: "module-panel__body", children: [_jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "Tipo" }), _jsxs("span", { className: `module-panel__badge module-panel__badge--${node.type}`, children: [node.type === 'module' && '📄 Archivo', node.type === 'folder' && '📁 Carpeta', node.type === 'database' && '🗄️ Base de datos', node.type === 'external_api' && '🌐 API externa'] })] }), isModule && (_jsxs(_Fragment, { children: [_jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "Ruta" }), _jsx("p", { className: "module-panel__code", children: node.path })] }), node.linesOfCode !== undefined && (_jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "L\u00EDneas de c\u00F3digo" }), _jsx("p", { className: "module-panel__text", children: node.linesOfCode?.toLocaleString() })] })), node.lastModified && (_jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "\u00DAltima modificaci\u00F3n" }), _jsx("p", { className: "module-panel__text", children: new Date(node.lastModified).toLocaleDateString('es-AR', {
                                            year: 'numeric',
                                            month: 'long',
                                            day: 'numeric',
                                        }) })] })), node.dependencies.length > 0 && (_jsxs("section", { className: "module-panel__section", children: [_jsxs("h3", { className: "module-panel__section-title", children: ["Dependencias (", node.dependencies.length, ")"] }), _jsx("ul", { className: "module-panel__list", children: node.dependencies.map((dep) => (_jsx("li", { className: "module-panel__list-item", children: _jsx("code", { className: "module-panel__code-inline", children: dep }) }, dep))) })] }))] })), isFolder && (_jsxs(_Fragment, { children: [_jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "Ruta" }), _jsx("p", { className: "module-panel__code", children: node.path })] }), _jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "Contenido" }), _jsxs("p", { className: "module-panel__text", children: [node.childCount, " elementos directos"] })] })] })), isIntegration && (_jsxs(_Fragment, { children: [_jsxs("section", { className: "module-panel__section", children: [_jsx("h3", { className: "module-panel__section-title", children: "Descripci\u00F3n" }), _jsx("p", { className: "module-panel__text", children: node.description })] }), _jsxs("section", { className: "module-panel__section", children: [_jsxs("h3", { className: "module-panel__section-title", children: ["Detectada en (", node.detectedIn.length, " m\u00F3dulos)"] }), _jsx("ul", { className: "module-panel__list", children: node.detectedIn.map((file) => (_jsx("li", { className: "module-panel__list-item", children: _jsx("code", { className: "module-panel__code-inline", children: file }) }, file))) })] })] }))] })] }));
};
